# version: "3"

# services:
#   oracledb:
#     build:
#       context: .
#       dockerfile: Dockerfile.db
#     ports:
#       - "1521:1521"
#     environment:
#       - ORACLE_PASSWORD=oracle
#       - ORACLE_DATABASE=QUANLYTRUONGDAIHOC
#     volumes:
#       - oracle-data:/opt/oracle/oradata
# volumes:
#   oracle-data:

# version: "3"

# services:
#   oracledb:
#     build:
#       context: .
#       dockerfile: Dockerfile.db
#     ports:
#       - "1521:1521"
#     environment:
#       - ORACLE_PASSWORD=oracle
#       - ORACLE_DATABASE=QUANLYTRUONGDAIHOC
#     volumes:
#       - oracle-data:/opt/oracle/oradata
# volumes:
#   oracle-data:

services:
  oracledb:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=QUANLYTRUONGDAIHOC
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:

