ALTER SESSION SET CONTAINER = QUANLYTRUONGDAIHOC;

CREATE USER QLTDH IDENTIFIED BY admin123;

-- Cấp quyền dba
-- USER SQL
ALTER USER "QLTDH"
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK 
ENABLE EDITIONS ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO "QLTDH" WITH ADMIN OPTION;
GRANT "CONNECT" TO "QLTDH" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "QLTDH" WITH ADMIN OPTION;
ALTER USER "QLTDH" DEFAULT ROLE "DBA";

-- SYSTEM PRIVILEGES
GRANT CREATE TABLE, CREATE USER, CREATE ROLE, CREATE TRIGGER, CREATE VIEW, CREATE SESSION, CREATE ANY SEQUENCE, CREATE ANY PROCEDURE TO "QLTDH" ;
GRANT ALTER USER, ALTER ANY ROLE, ALTER ANY TRIGGER, ALTER SESSION, ALTER ANY SEQUENCE TO "QLTDH" ;
GRANT DROP USER, DROP ANY ROLE, DROP ANY TRIGGER, DROP ANY VIEW, DROP ANY SEQUENCE, DROP ANY PROCEDURE TO "QLTDH" ;
GRANT SELECT ANY DICTIONARY TO "QLTDH" ;
GRANT UNLIMITED TABLESPACE TO "QLTDH" ;
GRANT GRANT ANY OBJECT PRIVILEGE, GRANT ANY PRIVILEGE TO "QLTDH" ;
GRANT EXECUTE ANY PROCEDURE TO "QLTDH" ;

-- -- Kiểm tra các vai trò đã cấp
-- SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'QLTDH';

-- -- Kiểm tra các quyền hệ thống đã cấp
-- SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'QLTDH';