ALTER SESSION SET CONTAINER = QUANLYTRUONGDAIHOC;

-- Xóa bảng nếu tồn tại
BEGIN
   -- Xóa bảng NHANVIEN nếu tồn tại
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE QLTDH.NHANVIEN CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN  -- Lỗi khác ngoài ORA-00942 (bảng không tồn tại)
            RAISE;
         END IF;
   END;

   -- Xóa bảng SINHVIEN nếu tồn tại
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE QLTDH.SINHVIEN CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

   -- Xóa bảng DONVI nếu tồn tại
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE QLTDH.DONVI CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

   -- Xóa bảng HOCPHAN nếu tồn tại
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE QLTDH.HOCPHAN CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

   -- Xóa bảng MOMON nếu tồn tại
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE QLTDH.MOMON CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

   -- Xóa bảng DANGKY nếu tồn tại
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE QLTDH.DANGKY CASCADE CONSTRAINTS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

END;
/

-- Bảng Nhân Viên
CREATE TABLE QLTDH.NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY, -- Mã nhân viên
    HOTEN VARCHAR2(100), -- Họ tên
    PHAI VARCHAR2(10) CHECK (PHAI IN ('Nam', 'Nữ')), -- Giới tính
    NGSINH DATE, -- Ngày sinh
    LUONG INTEGER, -- Lương
    PHUCAP INTEGER, -- Phụ cấp
    DT VARCHAR2(10) UNIQUE, -- Số điện thoại
    VAITRO VARCHAR2(7) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGĐV')), -- Vai trò
    MADV VARCHAR2(10) -- Mã đơn vị
);

-- Bảng Sinh Viên
CREATE TABLE QLTDH.SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY, -- Mã sinh viên
    HOTEN VARCHAR2(100), -- Họ tên
    PHAI VARCHAR2(10) CHECK (PHAI IN ('Nam', 'Nữ')), -- Giới tính
    NGSINH DATE, -- Ngày sinh
    DCHI VARCHAR2(200), -- Địa chỉ
    DT VARCHAR2(20) UNIQUE, -- Số điện thoại
    KHOA VARCHAR2(10), -- Khoa
    TINHTRANG VARCHAR2(20) CHECK (TINHTRANG IN ('Đang học', 'Nghỉ học', 'Bảo lưu')) -- Tình trạng
);

-- Bảng Đơn Vị
CREATE TABLE QLTDH.DONVI (
    MADV VARCHAR2(10) PRIMARY KEY, -- Mã đơn vị
    TENDV VARCHAR2(100) UNIQUE, -- Tên đơn vị
    LOAIDV VARCHAR2(10) CHECK (LOAIDV IN ('Khoa', 'Phòng')), -- Loại đơn vị
    TRGDV VARCHAR2(10) -- Trưởng đơn vị
);

-- Bảng Học Phần
CREATE TABLE QLTDH.HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY, -- Mã học phần
    TENHP VARCHAR2(100) UNIQUE, -- Tên học phần
    SOTC INTEGER, -- Số tín chỉ
    STLT INTEGER, -- Số tiết lý thuyết
    STTH INTEGER, -- Số tiết thực hành
    MADV VARCHAR2(10) -- Đơn vị phụ trách
);

-- Bảng Mở Môn
CREATE TABLE QLTDH.MOMON (
    MAMM VARCHAR2(10) PRIMARY KEY, -- Mã mở môn
    MAHP VARCHAR2(10), -- Mã học phần
    MAGV VARCHAR2(10), -- Giảng viên
    HK VARCHAR2(1) CHECK (HK IN ('1', '2', '3')), -- Học kỳ
    NAM INTEGER, -- Năm học
    UNIQUE (MAHP, MAGV, HK, NAM) -- Ràng buộc UNIQUE
);

-- Bảng Đăng Ký
CREATE TABLE QLTDH.DANGKY (
    MASV VARCHAR2(10), -- Mã sinh viên
    MAMM VARCHAR2(10), -- Mã môn
    DIEMTH NUMBER(5,2), -- Điểm thực hành
    DIEMQT NUMBER(5,2), -- Điểm quá trình
    DIEMCK NUMBER(5,2), -- Điểm cuối kỳ
    DIEMTK NUMBER(5,2), -- Điểm tổng kết
    PRIMARY KEY (MASV, MAMM)
);

-- NHANVIEN REF DONVI
ALTER TABLE QLTDH.NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_MADV FOREIGN KEY (MADV) REFERENCES QLTDH.DONVI (MADV);

-- SINHVIEN REF DONVI
ALTER TABLE QLTDH.SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY (KHOA) REFERENCES QLTDH.DONVI (MADV);

-- DONVI REF NHANVIEN
ALTER TABLE QLTDH.DONVI
ADD CONSTRAINT FK_DONVI_NHANVIEN FOREIGN KEY (TRGDV) REFERENCES QLTDH.NHANVIEN (MANV);

-- HOCPHAN REF DONVI
ALTER TABLE QLTDH.HOCPHAN
ADD CONSTRAINT FK_HOCPHAN_MADV FOREIGN KEY (MADV) REFERENCES QLTDH.DONVI (MADV);

-- MOMON REF HOCPHAN
ALTER TABLE QLTDH.MOMON
ADD CONSTRAINT FK_MOMON_MAHP FOREIGN KEY (MAHP) REFERENCES QLTDH.HOCPHAN (MAHP);

-- MOMON REF NHANVIEN
ALTER TABLE QLTDH.MOMON
ADD CONSTRAINT FK_MOMON_MAGV FOREIGN KEY (MAGV) REFERENCES QLTDH.NHANVIEN (MANV);

-- DANGKY REF SINHVIEN
ALTER TABLE QLTDH.DANGKY
ADD CONSTRAINT FK_DANGKY_MASV FOREIGN KEY (MASV) REFERENCES QLTDH.SINHVIEN (MASV);

-- DANGKY REF MOMON
ALTER TABLE QLTDH.DANGKY
ADD CONSTRAINT FK_DANGKY_MAMM FOREIGN KEY (MAMM) REFERENCES QLTDH.MOMON (MAMM);

-- Kiểm tra bảng đã tạo thành công chưa
SELECT TABLE_NAME, OWNER
FROM ALL_TABLES
WHERE OWNER = 'QLTDH';

