ALTER SESSION SET CONTAINER = QUANLYTRUONGDAIHOC;


--Đăng nhập bằng sys chạy trong root
--Cấu hình và kích hoạt OLS
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

--Kiểm tra lại trạng thái OLS:
SELECT NAME, STATUS, DESCRIPTION FROM DBA_OLS_STATUS;
--cấp quyền cho qltdh
ALTER SESSION SET CONTAINER = QUANLYTRUONGDAIHOC;
GRANT INHERIT PRIVILEGES ON USER LBACSYS TO QLTDH;
GRANT LBAC_DBA TO QLTDH;
GRANT EXECUTE ON SA_COMPONENTS TO QLTDH;
GRANT EXECUTE ON SA_LABEL_ADMIN TO QLTDH;
GRANT EXECUTE ON SA_POLICY_ADMIN TO QLTDH;
GRANT EXECUTE ON SA_USER_ADMIN TO QLTDH;
GRANT EXECUTE ON CHAR_TO_LABEL TO QLTDH;
--đăng nhập lại = qltdh 
--tạo bảng thông báo
CREATE TABLE QLTDH.THONGBAO (
  MATB        NUMBER PRIMARY KEY,
  TIEUDE     VARCHAR2(100),
  NOIDUNG    CLOB,
  THOIGIAN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DIADIEM    NVARCHAR2(50),
  OLS_LABEL  NUMBER   -- Cột nhãn bảo mật (OLS)
);
--cấp quyền
GRANT ALL ON QLTDH.THONGBAO TO LBACSYS;
GRANT ALL ON QLTDH.THONGBAO TO QLTDH;
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'QLTDH';

--Tạo ols policy
BEGIN
  SA_SYSDBA.CREATE_POLICY (
    policy_name     => 'THONGBAO_POLICY',
    column_name     => 'OLS_LABEL',
    default_options => 'READ_CONTROL,WRITE_CONTROL,LABEL_DEFAULT,NO_CONTROL'
  );
END;
/

--Tạo level (độ nhạy cảm)
BEGIN
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 10, 'THAP',   'Thông báo thường');
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 50, 'TRUNG',  'Thông báo nội bộ');
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 100,'CAO',    'Thông báo mật');
END;
/

--Tạo companent
BEGIN
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 1, 'CS1', 'Cơ sở 1');
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 2, 'CS2', 'Cơ sở 2');
END;
/

--Tạo group
BEGIN
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 10, 'TOAN',   'Khoa Toán');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 20, 'LY',     'Khoa Lý');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 30, 'HOA',    'Khoa Hóa');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 40, 'TCHC',   'Phòng Hành chính');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 50, 'PKT',    'Phòng Khảo thí');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 60, 'PDT',    'Phòng Đào tạo');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 70, 'CTSV',   'Phòng CTSV');
END;
/


BEGIN
  -- t1: Tất cả Trưởng đơn vị
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 101, 'ALL_TRGDV', 'CAO:CS1,CS2:TOAN,LY,HOA,TCHC,PKT,PDT,CTSV');

  -- t2: Tất cả Nhân viên
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 102, 'ALL_NV', 'TRUNG:CS1,CS2:TOAN,LY,HOA,TCHC,PKT,PDT,CTSV');

  -- t3: Tất cả Sinh viên (thay thế t7)
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 103, 'ALL_SV', 'THAP:CS1,CS2:TOAN,LY,HOA');

  -- t4: Sinh viên khoa Hóa CS1
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 104, 'SV_HOA_CS1', 'THAP:CS1:HOA');

  -- t5: Sinh viên khoa Hóa CS2
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 105, 'SV_HOA_CS2', 'THAP:CS2:HOA');

  -- t6: Sinh viên khoa Hóa cả hai cơ sở
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 106, 'SV_HOA_ALL', 'THAP:CS1,CS2:HOA');

  -- t8: Trưởng khoa Hóa CS1
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 108, 'TRGDV_HOA_CS1', 'CAO:CS1:HOA');

  -- t9: Trưởng khoa Hóa cả hai cơ sở
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 109, 'TRGDV_HOA_ALL', 'CAO:CS1,CS2:HOA');
END;
/

--Gán nhãn cho người dùng
BEGIN
  -- u1: Trưởng đơn vị – đọc tất cả thông báo
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U1', 'CAO:CS1,CS2:TOAN,LY,HOA,TCHC,PKT,PDT,CTSV');

  -- u2: Trưởng khoa Hóa tại CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U2', 'CAO:CS2:HOA');

  -- u3: Trưởng khoa Lý tại CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U3', 'CAO:CS2:LY');

  -- u4: Nhân viên khoa Hóa tại CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U4', 'TRUNG:CS2:HOA');

  -- u5: Sinh viên khoa Hóa tại CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U5', 'THAP:CS2:HOA');

  -- u6: Trưởng đơn vị Hành chính
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U6', 'CAO:CS1,CS2:TCHC');

  -- u7: Nhân viên – đọc tất cả thông báo cho Nhân viên
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U7', 'TRUNG:CS1,CS2:TOAN,LY,HOA,TCHC,PKT,PDT,CTSV');

  -- u8: Nhân viên Hành chính tại CS1
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U8', 'TRUNG:CS1:TCHC');
END;
/

--Gán chính sách vào bảng thông báo
BEGIN
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name    => 'THONGBAO_POLICY',
    schema_name    => 'QLTDH',
    table_name     => 'THONGBAO',
    table_options  => 'LABEL_DEFAULT'
  );
END;
/


--Kiểm tra
-- Chèn dữ liệu mẫu có gán nhãn OLS
INSERT INTO QLTDH.THONGBAO (MATB, TIEUDE, NOIDUNG, DIADIEM, OLS_LABEL) VALUES (
  1, 'Họp trưởng đơn vị', 'Họp tổng kết năm học', 'Phòng A1', 101
);
INSERT INTO QLTDH.THONGBAO (MATB, TIEUDE, NOIDUNG, DIADIEM, OLS_LABEL) VALUES (
  2, 'Lịch học Hóa CS2', 'Lịch thực hành bổ sung', 'CS2 - P.202', 105
);

INSERT INTO QLTDH.THONGBAO (MATB, TIEUDE, NOIDUNG, DIADIEM, OLS_LABEL) VALUES (
  3, 'Xét lương mới', 'Quy trình xét lương', 'Văn phòng', 102
);

CONNECT U1/password;

-- Người dùng được phép truy cập
CONNECT GV_CNTT_CS1/password;
SELECT * FROM QLTDH.THONGBAO;

-- Người không được cấp nhãn phù hợp → không thấy dữ liệu
CONNECT KHACUSER/password;
SELECT * FROM QLTDH.THONGBAO;


