-- Kết nối bằng SYSDBA trong XE
-- Đảm bảo đang ở ROOT
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- Để hiển thị output
SET SERVEROUTPUT ON;

-- Kiểm tra kết nối
SELECT SYS_CONTEXT('USERENV', 'CON_NAME'), USER FROM DUAL;

-- Kiểm tra PDB, đóng nếu đang mở và xóa
DECLARE
    v_count NUMBER;
    v_open_mode VARCHAR2(20);
BEGIN
    -- Kiểm tra PDB có tồn tại không
    SELECT COUNT(*) INTO v_count
    FROM DBA_PDBS
    WHERE PDB_NAME = 'QUANLYTRUONGDAIHOC';

    IF v_count = 1 THEN
        -- Kiểm tra trạng thái mở của PDB từ V$PDBS
        SELECT OPEN_MODE INTO v_open_mode
        FROM V$PDBS
        WHERE NAME = 'QUANLYTRUONGDAIHOC';

        -- Nếu PDB đang mở thì đóng lại
        IF v_open_mode != 'MOUNTED' THEN
            EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE QUANLYTRUONGDAIHOC CLOSE IMMEDIATE';
        END IF;

        -- Sau đó xóa PDB
        EXECUTE IMMEDIATE 'DROP PLUGGABLE DATABASE QUANLYTRUONGDAIHOC INCLUDING DATAFILES';
        DBMS_OUTPUT.PUT_LINE('PDB QUANLYTRUONGDAIHOC đã được xóa.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PDB QUANLYTRUONGDAIHOC không tồn tại.');
    END IF;
END;
/

-- Kiểm tra đã xóa pdb thành công chưa(nếu có).
SELECT PDB_NAME from DBA_PDBS;

-- Xóa dba nếu đã được tạo
DECLARE
    -- Biến kiểm tra sự tồn tại của người dùng
    user_exists INTEGER;
BEGIN
    -- Kiểm tra sự tồn tại của người dùng QLTDH trong cơ sở dữ liệu
    SELECT COUNT(*) INTO user_exists
    FROM all_users
    WHERE username = 'QLTDH';
 
    -- Nếu người dùng tồn tại, thực hiện các thao tác
    IF user_exists > 0 THEN
        -- Thu hồi quyền DBA nếu người dùng có quyền này
        BEGIN
            EXECUTE IMMEDIATE 'REVOKE DBA FROM QLTDH';
        EXCEPTION
            WHEN OTHERS THEN
                NULL; -- Bỏ qua nếu không có quyền DBA
        END;
 
        -- Xóa người dùng và tất cả các đối tượng liên quan
        EXECUTE IMMEDIATE 'DROP USER QLTDH CASCADE';
        DBMS_OUTPUT.PUT_LINE('Người dùng QLTDH đã được xóa.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Người dùng QLTDH không tồn tại.');
    END IF;
END;
/
--Xoa PDB
--ALTER SESSION SET CONTAINER=CDB$ROOT;
--ALTER PLUGGABLE DATABASE QUANLYTRUONGDAIHOC CLOSE IMMEDIATE;
--DROP PLUGGABLE DATABASE QUANLYTRUONGDAIHOC INCLUDING DATAFILES;
-- Tạo database
CREATE PLUGGABLE DATABASE QUANLYTRUONGDAIHOC
ADMIN USER QLTDH IDENTIFIED BY admin123
FILE_NAME_CONVERT = ('C:\APP\VAN\PRODUCT\21C\ORADATA\XE\PDBSEED\', 
                     'C:\APP\VAN\PRODUCT\21C\ORADATA\XE\QUANLYTRUONGDAIHOC\'); -- Thay đường dẫn

-- Mở kết nối database
ALTER PLUGGABLE DATABASE QUANLYTRUONGDAIHOC OPEN;  
ALTER SESSION SET CONTAINER = QUANLYTRUONGDAIHOC;

-- Kiểm tra kết nối
SELECT SYS_CONTEXT('USERENV', 'CON_NAME'), USER FROM DUAL;

-- Cấp quyền dba
-- USER SQL
ALTER USER "QLTDH"
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK 
ENABLE EDITIONS ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO "QLTDH" WITH ADMIN OPTION;
GRANT "CONNECT" TO "QLTDH" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "QLTDH" WITH ADMIN OPTION;
ALTER USER "QLTDH" DEFAULT ROLE "DBA","PDB_DBA";

-- SYSTEM PRIVILEGES
GRANT CREATE TABLE, CREATE USER, CREATE ROLE, CREATE TRIGGER, CREATE VIEW, CREATE SESSION, CREATE ANY SEQUENCE, CREATE ANY PROCEDURE TO "QLTDH" ;
GRANT ALTER USER, ALTER ANY ROLE, ALTER ANY TRIGGER, ALTER SESSION, ALTER ANY SEQUENCE TO "QLTDH" ;
GRANT DROP USER, DROP ANY ROLE, DROP ANY TRIGGER, DROP ANY VIEW, DROP ANY SEQUENCE, DROP ANY PROCEDURE TO "QLTDH" ;
GRANT SELECT ANY DICTIONARY TO "QLTDH" ;
GRANT UNLIMITED TABLESPACE TO "QLTDH" ;
GRANT GRANT ANY OBJECT PRIVILEGE, GRANT ANY PRIVILEGE TO "QLTDH" ;
GRANT EXECUTE ANY PROCEDURE TO "QLTDH" ;

-- Kiểm tra các vai trò đã cấp
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'QLTDH';

-- Kiểm tra các quyền hệ thống đã cấp
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'QLTDH';