-- Kiểm tra đã kết nối chưa
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') FROM DUAL;
SELECT USER FROM DUAL;

-- Xóa dữ liệu cũ nếu đã có
TRUNCATE TABLE NHANVIEN;
TRUNCATE TABLE SINHVIEN;
TRUNCATE TABLE DONVI;
TRUNCATE TABLE HOCPHAN;
TRUNCATE TABLE MOMON;
TRUNCATE TABLE DANGKY;

-- Nhập dữ liệu cho bảng DONVI
-- Khoa
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('CNT', 'Công nghệ thông tin', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('VLK', 'Vật lý - Vật lý kỹ thuật', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('DC', 'Địa chất', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('TTTH', 'Toán - Tin học', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('ETVT', 'Điện tử - Viễn thông', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KHCN', 'Khoa học công nghệ và vật liệu', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('HH', 'Hóa học', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('SHCN', 'Sinh học - Công nghệ sinh học', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('MT', 'Môi trường', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KHLN', 'Khoa học liên ngành', 'Khoa', NULL);
-- Phòng
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PĐT', 'Phòng Đào tạo', 'Phòng', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PKT', 'Phòng Khảo thí', 'Phòng', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PTTCHC', 'Phòng Tổ chức hành chính', 'Phòng', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PCTSV', 'Phòng Công tác sinh viên', 'Phòng', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PKHCN', 'Phòng Khoa học công nghệ', 'Phòng', NULL);
-- Kiểm tra dữ liệu của DONVI
SELECT * FROM DONVI;










